[project]
name = "ecommerce-platform"
version = "0.1.0"
requires-python = ">=3.13"

[tool.uv]
package = false

[tool.uv.workspace]
members = [
  "core-common",
  "msg-common",
  "auth-service",
  "user-service",
  "product-service",
  "order-service",
  "payment-service",
  "invoice-service",
  "notification-service",
  "workflow-service",
]

[tool.uv.sources]
core-common = { workspace = true }
msg-common = { workspace = true }
