# Database persistence type.
conductor.db.type=postgres
conductor.queue.type=postgres
conductor.external-payload-storage.type=postgres

# Database connectivity.
spring.datasource.url=jdbc:postgresql://postgres:5432/conductor_db
spring.datasource.username=ecom
spring.datasource.password=ecom

# Index workflows into Postgres and disable Elasticsearch.
conductor.indexing.enabled=true
conductor.indexing.type=postgres
conductor.elasticsearch.version=0

# Local development metrics.
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

loadSample=false
